### ISSUE TITLE
Success or Invalid Notification frames wrapping around the text in them

### ISSUE THREAD

**Issue by StefanTotev** [CJSCommonPlatform/ngGovUk#29]
Hello,

Whenever I'm using the Notification frames, they appear throughout the whole length of the screen like this:

<img width="1191" alt="screen shot 2016-03-31 at 17 16 13" src="https://cloud.githubusercontent.com/assets/6977246/14182713/73a0452c-f764-11e5-8cb6-a1ede63846aa.png">

Would it be possible for the frame to wrap around the text inside like:

![image](https://cloud.githubusercontent.com/assets/6977246/14182522/778cf4c4-f763-11e5-8ec1-942dd37874c6.png)

**Comment by vygis** [comment]
@StefanTotev since the notification is a `<div>`, it takes up the full width of the parent container.

I would suggest to use wrap your notifications in the boostrap grid classes, see example plunkr:

[http://embed.plnkr.co/TyiLQfB75egemlMv3FMO/](http://embed.plnkr.co/TyiLQfB75egemlMv3FMO/)

I'll add some right padding so that words are wrapped nicely for all cases.
